# This file was generated by GoReleaser. DO NOT EDIT.
cask "dotfiles" do
  version "1.9.0"

  on_macos do
    on_intel do
      sha256 "7be08892bf1c654d70bd13a9d352e171017f797764d48b56aef3476a44dbc8c2"
      url "https://gitlab.com/pidrakin/dotfiles-cli/-/releases/v#{version}/downloads/dotfiles-#{version}-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "2920f60967ee35ac8243a94054b5a211eee659845d2cc51376571326b724a297"
      url "https://gitlab.com/pidrakin/dotfiles-cli/-/releases/v#{version}/downloads/dotfiles-#{version}-darwin-arm64.tar.gz"
    end
  end

  name "dotfiles"
  desc "This tool encourages and supports creating, maintaining and distributing a set of dotfiles. Dotfiles encompasses the relevant configuration files accompanying most of the binaries, tools on nix-themed systems."
  homepage "https://gitlab.com/pidrakin/dotfiles-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dotfiles"
  manpage "man/dotfiles-completion.1.gz"
  manpage "man/dotfiles-config.1.gz"
  manpage "man/dotfiles-diff.1.gz"
  manpage "man/dotfiles-eject.1.gz"
  manpage "man/dotfiles-init.1.gz"
  manpage "man/dotfiles-install.1.gz"
  manpage "man/dotfiles-link.1.gz"
  manpage "man/dotfiles-remote.1.gz"
  manpage "man/dotfiles-repoconfig.1.gz"
  manpage "man/dotfiles-rollout.1.gz"
  manpage "man/dotfiles-stateconfig.1.gz"
  manpage "man/dotfiles-status.1.gz"
  manpage "man/dotfiles-unlink.1.gz"
  manpage "man/dotfiles.1.gz"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dotfiles"]
    end
  end
  generate_completions_from_executable "dotfiles",
    shell_parameter_format: :cobra,
    shells: [:bash]

  # No zap stanza required

  caveats <<~EOS
    You do not need to reinstall after normal cask upgrades.
    Only uninstall the old formula if `brew list --formula dotfiles` still shows one,
    or if `which dotfiles` does not point to the cask binary:
      brew uninstall --formula dotfiles
      brew install --cask pidrakin/dotfiles/dotfiles
  EOS
end
