# This file was generated by GoReleaser. DO NOT EDIT.
cask "dotfiles" do
  version "1.10.0"

  on_macos do
    on_intel do
      sha256 "a9f3379788bcda390dfcf2d5fff60d2366d03fe692ea8c2ae1403d3bc956fb91"
      url "https://gitlab.com/pidrakin/dotfiles-cli/-/releases/v#{version}/downloads/dotfiles-#{version}-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "b9d882dfc316a6deb42e5fb1e8fbcb1a5eb50f32a076387b0c4993c420c5f276"
      url "https://gitlab.com/pidrakin/dotfiles-cli/-/releases/v#{version}/downloads/dotfiles-#{version}-darwin-arm64.tar.gz"
    end
  end

  name "dotfiles"
  desc "This tool encourages and supports creating, maintaining and distributing a set of dotfiles. Dotfiles encompasses the relevant configuration files accompanying most of the binaries, tools on nix-themed systems."
  homepage "https://gitlab.com/pidrakin/dotfiles-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dotfiles"
  manpage "man/dotfiles-completion.1.gz"
  manpage "man/dotfiles-config.1.gz"
  manpage "man/dotfiles-diff.1.gz"
  manpage "man/dotfiles-eject.1.gz"
  manpage "man/dotfiles-init.1.gz"
  manpage "man/dotfiles-install.1.gz"
  manpage "man/dotfiles-link.1.gz"
  manpage "man/dotfiles-remote.1.gz"
  manpage "man/dotfiles-repoconfig.1.gz"
  manpage "man/dotfiles-rollout.1.gz"
  manpage "man/dotfiles-stateconfig.1.gz"
  manpage "man/dotfiles-status.1.gz"
  manpage "man/dotfiles-unlink.1.gz"
  manpage "man/dotfiles.1.gz"
  bash_completion "completions/dotfiles.bash"

  # No zap stanza required

  caveats <<~EOS
    You do not need to reinstall after normal cask upgrades.
    Only uninstall the old formula if `brew list --formula dotfiles` still shows one,
    or if `which dotfiles` does not point to the cask binary:
      brew uninstall --formula dotfiles
      brew install --cask pidrakin/dotfiles/dotfiles
  EOS
end
