# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdtool" do
  name "mdtool"
  desc "Render templated Markdown documents to HTML or PDF with Chromium."
  homepage "https://gitlab.com/pidrakin/mdtool"
  version "0.6.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdtool"

  on_macos do
    on_arm do
      url "https://gitlab.com/pidrakin/mdtool/-/releases/#{version}/downloads/mdtool-#{version}-darwin-arm64.tar.gz"
      sha256 "9e56a4336ed85edc17993f5b0ba0b65e5a7d69ce4d40a34600b757a079d40f08"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mdtool"]
  end

  caveats do
    <<~EOS
      You do not need to reinstall after normal cask upgrades.
      Only uninstall the old formula if `brew list --formula mdtool` still shows one,
      or if `which mdtool` does not point to the cask binary:
        brew uninstall mdtool
        brew install --cask pidrakin/dotfiles/mdtool

      Install Google Chrome or Chromium if you want to generate PDFs with the native binary.
      Set MDTOOL_BROWSER when auto-discovery is not sufficient.

      PlantUML code fences also require a Java runtime and the plantuml executable in PATH.
    EOS
  end

  # No zap stanza required
end
