# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdtool" do
  version "0.13.1"

  on_macos do
    on_arm do
      sha256 "08a4cdb5a3a9b12e97c550533d8234a7ec299f7e97653818f296b22a59b9b27f"
      url "https://gitlab.com/pidrakin/mdtool/-/releases/v#{version}/downloads/mdtool-#{version}-darwin-arm64.tar.gz"
    end
  end

  name "mdtool"
  desc "Render templated Markdown documents to HTML or PDF with Chromium."
  homepage "https://gitlab.com/pidrakin/mdtool"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdtool"
  bash_completion "completions/mdtool.bash"
  fish_completion "completions/mdtool.fish"
  zsh_completion "completions/mdtool.zsh"

  # No zap stanza required

  caveats <<~EOS
    You do not need to reinstall after normal cask upgrades.
    Only uninstall the old formula if `brew list --formula mdtool` still shows one,
    or if `which mdtool` does not point to the cask binary:
      brew uninstall mdtool
      brew install --cask pidrakin/dotfiles/mdtool

    Install Google Chrome or Chromium if you want to generate PDFs with the native binary.
    Set MDTOOL_BROWSER when auto-discovery is not sufficient.

    PlantUML code fences also require a Java runtime and the plantuml executable in PATH.
  EOS
end
