# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dotfiles < Formula
  desc "This tool encourages and supports creating, maintaining and distributing a set of dotfiles. Dotfiles encompasses the relevant configuration files accompanying most of the binaries, tools on nix-themed systems."
  homepage "https://gitlab.com/pidrakin/dotfiles-cli"
  version "1.8.0-rc.26"
  license "HOOKAH-WARE"

  depends_on "bash-completion@2"
  depends_on :macos

  on_intel do
    url "https://gitlab.com/pidrakin/dotfiles-cli/-/releases/v1.8.0-rc.26/downloads/dotfiles-1.8.0-rc.26-darwin-amd64.tar.gz"
    sha256 "ebb5c25a8c2eb87792b04ba1dff1226af21c3f2730b086a2acb38248caab095b"

    def install
      bin.install "dotfiles"
      man1.install Dir["man/*"]
      doc.install Dir["docs/*"]
      doc.install "LICENSE"
      doc.install "README.md"
      doc.install "preview.png"
      generate_completions_from_executable(bin/"dotfiles", shell_parameter_format: :cobra, shells: [:bash])
    end
  end
  on_arm do
    url "https://gitlab.com/pidrakin/dotfiles-cli/-/releases/v1.8.0-rc.26/downloads/dotfiles-1.8.0-rc.26-darwin-arm64.tar.gz"
    sha256 "f993cc2f3b3da81c58c3000c575427ddd6816e09e523288d9a67a09856c3300a"

    def install
      bin.install "dotfiles"
      man1.install Dir["man/*"]
      doc.install Dir["docs/*"]
      doc.install "LICENSE"
      doc.install "README.md"
      doc.install "preview.png"
      generate_completions_from_executable(bin/"dotfiles", shell_parameter_format: :cobra, shells: [:bash])
    end
  end

  test do
    system "#{bin}/dotfiles --version"
  end
end
