# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dotfiles < Formula
  desc "This tool encourages and supports creating, maintaining and distributing a set of dotfiles. Dotfiles encompasses the relevant configuration files accompanying most of the binaries, tools on nix-themed systems."
  homepage "https://gitlab.com/pidrakin/dotfiles-cli"
  version "1.8.0"
  license "HOOKAH-WARE"

  depends_on "bash-completion@2"
  depends_on :macos

  on_intel do
    url "https://gitlab.com/pidrakin/dotfiles-cli/-/releases/v1.8.0/downloads/dotfiles-1.8.0-darwin-amd64.tar.gz"
    sha256 "015947e5d9219f00ff69bf47e6f3cfd3725954e055e13f51bbfff18c3ceab2cf"

    def install
      bin.install "dotfiles"
      man1.install Dir["man/*"]
      doc.install Dir["docs/*"]
      doc.install "LICENSE"
      doc.install "README.md"
      doc.install "preview.png"
      generate_completions_from_executable(bin/"dotfiles", shell_parameter_format: :cobra, shells: [:bash])
    end
  end
  on_arm do
    url "https://gitlab.com/pidrakin/dotfiles-cli/-/releases/v1.8.0/downloads/dotfiles-1.8.0-darwin-arm64.tar.gz"
    sha256 "31ef9a8937917e873f6ce751939dc112368b59e333dd0ac45745c490a4750d30"

    def install
      bin.install "dotfiles"
      man1.install Dir["man/*"]
      doc.install Dir["docs/*"]
      doc.install "LICENSE"
      doc.install "README.md"
      doc.install "preview.png"
      generate_completions_from_executable(bin/"dotfiles", shell_parameter_format: :cobra, shells: [:bash])
    end
  end

  test do
    system "#{bin}/dotfiles --version"
  end
end
