# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dotfiles < Formula
  desc "This tool encourages and supports creating, maintaining and distributing a set of dotfiles. Dotfiles encompasses the relevant configuration files accompanying most of the binaries, tools on nix-themed systems."
  homepage "https://gitlab.com/pidrakin/dotfiles-cli"
  version "1.8.0-rc.25"
  license "HOOKAH-WARE"

  depends_on "bash-completion@2"
  depends_on :macos

  on_intel do
    url "https://gitlab.com/pidrakin/dotfiles-cli/-/releases/v1.8.0-rc.25/downloads/dotfiles-1.8.0-rc.25-darwin-amd64.tar.gz"
    sha256 "1eefb84fd3750c286dbc835d91bac47a7d7d1809ac733f52587bdfeb9de41741"

    def install
      bin.install "dotfiles"
      man1.install Dir["man/*"]
      doc.install Dir["docs/*"]
      doc.install "LICENSE"
      doc.install "README.md"
      doc.install "preview.png"
      generate_completions_from_executable(bin/"dotfiles", shell_parameter_format: :cobra, shells: [:bash])
    end
  end
  on_arm do
    url "https://gitlab.com/pidrakin/dotfiles-cli/-/releases/v1.8.0-rc.25/downloads/dotfiles-1.8.0-rc.25-darwin-arm64.tar.gz"
    sha256 "a7f8820c09b376f199d6db0b0ca5b258e9c5f49034b0b095d7fa8f04d2517427"

    def install
      bin.install "dotfiles"
      man1.install Dir["man/*"]
      doc.install Dir["docs/*"]
      doc.install "LICENSE"
      doc.install "README.md"
      doc.install "preview.png"
      generate_completions_from_executable(bin/"dotfiles", shell_parameter_format: :cobra, shells: [:bash])
    end
  end

  test do
    system "#{bin}/dotfiles --version"
  end
end
