# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdtool < Formula
  desc "Render templated Markdown documents to HTML or PDF with Chromium."
  homepage "https://gitlab.com/pidrakin/mdtool"
  version "0.5.2-beta.15"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://gitlab.com/pidrakin/mdtool/-/releases/0.5.2-beta.15/downloads/mdtool-0.5.2-beta.15-darwin-arm64.tar.gz"
    sha256 "2e6d0650b19d5d3194598fe41a95773beaebe86e58cc22c335443487c3c45dff"

    define_method(:install) do
      bin.install "mdtool"
      doc.install "LICENSE"
      doc.install "README.md"
    end
  end

  def caveats
    <<~EOS
      Install Google Chrome or Chromium if you want to generate PDFs with the native binary.
      Set MDTOOL_BROWSER when auto-discovery is not sufficient.

      PlantUML code fences also require a Java runtime and the plantuml executable in PATH.
    EOS
  end

  test do
    system "#{bin}/mdtool", "--version"
  end
end
